method: grid
name: sweep
metric:
  goal: minimize
  name: avg_loss_test
parameters:
  batch_size:
    values:
      - 512
  weight_decay:
    values:
      - 0.0001
  num_ops:
    values:
      - 4
  magnitude:
    values:
      - 8  
  num_epochs:
    values:
      - 180
  lr:
    values:
      - 0.001
  dropout:
    values:
      - 0.0
  dim:
    values:
      - 128
  depth:
    values:
      - 8
  heads:
    values:
      - 4
  mlp_dim:
    values:
      - 256
  routing:
    values:
      - standard
      - tokenChoice
      - expertChoice
      - muxAllTokens
      - muxKTokens
  nOfExperts:
    values:
      - -1
      - 16
      - 64
  k:
    values:
      - -1
      - 1
      - 2
      - 4
  useSphere:
    values:
      - False
      - True
