method: grid
name: sweep
metric:
  goal: minimize
  name: avg_loss_test
early_terminate: None
parameters:
  batch_size:
    values:
      - 128
  weight_decay:
    values:
      - 0.0001
  num_ops:
    values:
      - 3
  magnitude:
    values:
      - 12  
  num_epochs:
    values:
      - 200
  lr:
    values:
      - 0.0001
  dropout:
    values:
      - 0.05
  dim:
    values:
      - 128
  depth:
    values:
      - 12
  heads:
    values:
      - 4
  mlp_dim:
    values:
      - 256
  routing:
    values:
      - standard
      - tokenChoice
      - expertChoice
      - muxAllTokens
      - muxKTokens
  nOfExperts:
    values:
      - -1
      - 16
      - 64
      - 128
  k:
    values:
      - -1
      - 1
      - 2
      - 4
  useSphere:
    values:
      - False
     
