method: grid
name: sweep
metric:
  goal: minimize
  name: avg_loss_test
parameters:
  batch_size:
    values:
      - 512
  num_epochs:
    values:
      - 180
  lr:
    values:
      - 0.001
  dim:
    values:
      - 256
  depth:
    values:
      - 12
  heads:
    values:
      - 12
  mlp_dim:
    values:
      - 512
  routing:
    values:
      - standard
      - tokenChoice
      - expertChoice
      - muxAllTokens
      - muxKTokens
  nOfExperts:
    values:
      - -1
      - 16
      - 64
  k:
    values:
      - -1
      - 1
      - 2
      - 4
  useSphere:
    values:
      - False
      - True
