method: grid
name: sweep
metric:
  goal: minimize
  name: loss
parameters:
  batch_size:
    values:
      - 128
  num_epochs:
    values:
      - 1
  lr:
    values:
      - 0.0001
  dim:
    values:
      - 128
  depth:
    values:
      - 2
  heads:
    values:
      - 8
  mlp_dim:
    values:
      - 128
  routing:
    values:
      - standard
      - tokenChoice
      - expertChoice
      - muxAllTokens
      - muxKTokens
  nOfExperts:
    values:
      - -1
      - 16
      - 64
      - 128
    # when: routing == expertChoice or routing == tokenChoice or routing == muxKTokens or routing == muxAllTokens
  k:
    values:
      - -1
      - 1
      - 2
      - 4
    # when: routing == expertChoice or routing == muxKTokens or routing == muxAllTokens
  useSphere:
    values:
      - False
      - True
    # when: routing == expertChoice or routing == muxKTokens or routing == muxAllTokens