method: grid
name: sweep
metric:
  goal: minimize
  name: avg_loss_test
parameters:
  batch_size:
    values:
      - 128
  num_epochs:
    values:
      - 100
  lr:
    values:
      - 0.0001
  dim:
    values:
      - 128
  depth:
    values:
      - 3
  heads:
    values:
      - 8
  mlp_dim:
    values:
      - 128
  routing:
    values:
      - standard
      - tokenChoice
      - expertChoice
      - muxAllTokens
      - muxKTokens
  nOfExperts:
    values:
      - -1
      - 16
      - 64
      - 128
      - 256
  k:
    values:
      - -1
      - 1
      - 2
      - 4
  useSphere:
    values:
      - False
      - True
